### ISSUE TITLE
ssh -T git@github.com Permission denied (publickey).

### ISSUE THREAD

**Issue by claudiomanuelboston** [susanBuck/e28-fall19#6]
I am getting the following issue 

$ ssh -T git@github.com
Warning: Permanently added the RSA host key for IP address '1.1.1.1' to the list of known hosts.
git@github.com: Permission denied (publickey).

**Comment by susanBuck** [comment]
@claudiomanuelboston Can you run the command `ssh -vT git@github.com` and share the output with us? This will report more details about the connection attempt.

For reference, this suggestion from [this resource](https://help.github.com/en/articles/error-permission-denied-publickey) linked from the ["Github" note set](https://hesweb.dev/e28/notes#/git/github?jump=test-it). There's some other useful tips there that may help you resolve the issue.

**Comment by claudiomanuelboston** [comment]
$ ssh -vT git@github.com
OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to github.com [192.30.253.112] port 22.
debug1: Connection established.
debug1: identity file /c/Users/claud/.ssh/id_rsa type -1
debug1: identity file /c/Users/claud/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/claud/.ssh/id_dsa type -1
debug1: identity file /c/Users/claud/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/claud/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/claud/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/claud/.ssh/id_ed25519 type -1
debug1: identity file /c/Users/claud/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/claud/.ssh/id_xmss type -1
debug1: identity file /c/Users/claud/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.0
debug1: Remote protocol version 2.0, remote software version babeld-6c2374e6
debug1: no match: babeld-6c2374e6
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC:
<implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC:
<implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa
SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /c/Users/claud/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /c/Users/claud/.ssh/id_rsa
debug1: Will attempt key: /c/Users/claud/.ssh/id_dsa
debug1: Will attempt key: /c/Users/claud/.ssh/id_ecdsa
debug1: Will attempt key: /c/Users/claud/.ssh/id_ed25519
debug1: Will attempt key: /c/Users/claud/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info:
server-sig-algs=<ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /c/Users/claud/.ssh/id_rsa
debug1: Trying private key: /c/Users/claud/.ssh/id_dsa
debug1: Trying private key: /c/Users/claud/.ssh/id_ecdsa
debug1: Trying private key: /c/Users/claud/.ssh/id_ed25519
debug1: Trying private key: /c/Users/claud/.ssh/id_xmss
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).

**Comment by susanBuck** [comment]
From that output, note the following section:

```
debug1: Trying private key: /c/Users/claud/.ssh/id_rsa
debug1: Trying private key: /c/Users/claud/.ssh/id_dsa
debug1: Trying private key: /c/Users/claud/.ssh/id_ecdsa
debug1: Trying private key: /c/Users/claud/.ssh/id_ed25519
debug1: Trying private key: /c/Users/claud/.ssh/id_xmss
```

Note how it's not listing the key `e28` which should have been configured, per the notes.

* Can you confirm and double check you created a key pair called `e28`?
* If you can, can you confirm and double checked you [edited your SSH config file to use this key](https://hesweb.dev/e28/notes#/git/github?jump=ssh-config-file)?

**Comment by susanBuck** [comment]
Side note: When sharing things like error messages (first thread), or error log output (your most recent thread), please use Markdown code blocks so everything is more legible. Examples/details shown here: [Example post demonstrating Markdown features](https://github.com/susanBuck/e28-fall19/issues/2)

**Comment by claudiomanuelboston** [comment]
Yes,
Here is the GitHub repo
 and the keys
[image: image.png]
[image: image.png]

**Comment by susanBuck** [comment]
Ok - In a separate email, you noted that you could connect with the key if explicitly specified it as part of the connection:

```
ssh -T -i %homepath%/.ssh/e28 git@github.com
```

This confirms the key exists/functions, it's just not being used. This may be because it wasn't set up in your SSH config file. Can you [confirm the steps described here](https://hesweb.dev/e28/notes#/git/github?jump=ssh-config-file) and share the contents of your SSH config file?

**Comment by claudiomanuelboston** [comment]
Here are the contents of the SSH config file, I confirmed the steps a
couple of times

IdentityFile ~/.ssh/e28

**Comment by claudiomanuelboston** [comment]
Also, the config file didn't exist so I ended up creating with nano config
command

**Comment by susanBuck** [comment]
Ok - I've got to step away for the day so I can't continue troubleshooting right now. But - In the interim - since you know your key is functional, you can manually specify it as a needed using the `-i` identity flag.

For example, when trying to clone (#7), add `-i %homepath%/.ssh/e28` to your command, like so:

```
git clone -i %homepath%/.ssh/e28 git@github.com:claudiomanuelboston/e28.git
```

That should hold you over for now. I'll check in on this again Monday so we can resolve the underlying issue - or perhaps a classmate has an idea of something to try in the meantime. : )

**Comment by susanBuck** [comment]
Correction - ignore my last post: 

The `-i` flag only works with `ssh` commands (like `ssh -T -i %homepath%/.ssh/e28 git@github.com`). It won't work with straight `git` commands.

Please hold while I come up with another alternative/temporary solution. : )

**Comment by claudiomanuelboston** [comment]
Ok, thank you very much

**Comment by susanBuck** [comment]
I was looking closer at the output from the `ssh -vT git@github.com` command you shared above:

```
$ ssh -vT git@github.com
OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
debug1: Reading configuration data /etc/ssh/ssh_config
```

Note how it says it's reading config data from `/etc/ssh/ssh_config`, which is not the SSH config file we're using.

For comparison, mine says:
```
debug1: Reading configuration data C:\\Users\\Susan/.ssh/config
```

This is the expected path; it's equivalent to `%homepath%/.ssh/config`.

In my research, I found [an instance where restarting Cmder fixed the issue](https://github.com/cmderdev/cmder/issues/58). 

I'm wondering if you had started Cmder before you had created `%homepath%/.ssh/config` and so now it's not registering it. According to [this thread](https://github.com/cmderdev/cmder/issues/978) `/etc/ssh/ssh_config` is the other default location Cmder looks for the SSH config file.

__Try closing and restarting Cmder and see if that resolves the issue.__

If that doesn't do the trick - are you free sometime tomorrow (Monday) where we could connect via screenshare and troubleshoot this in real time?

**Comment by claudiomanuelboston** [comment]
Hello,
I fixed this issue : debug1: Reading configuration data
C:\\Users\\Susan/.ssh/config, It is point to the right place. I will
continue working in it today and will can do screen share tomorrow. Have a
good afternoon Claudio

**Comment by gpunzalan18** [comment]
I was also facing a similar issue (mac):

Here are the logs:
```
gp-computer:~ gracepunzalan$ ssh -vT git@github.com
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/gracepunzalan/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: Connecting to github.com port 22.
debug1: Connection established.
debug1: identity file /Users/gracepunzalan/.ssh/e28 type 0
debug1: identity file /Users/gracepunzalan/.ssh/e28-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
debug1: Remote protocol version 2.0, remote software version babeld-6c2374e6
debug1: no match: babeld-6c2374e6
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /Users/gracepunzalan/.ssh/known_hosts:4
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
<b>debug1: Will attempt key: /Users/gracepunzalan/.ssh/e28 RSA SHA256:75sSuMYmP23ZJATLN9EJMBCXrsHmGuHsub+b5gpMs8w explicit<b>
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/gracepunzalan/.ssh/e28 RSA SHA256:75sSuMYmP23ZJATLN9EJMBCXrsHmGuHsub+b5gpMs8w explicit
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).
```
In my case though, it seemed that my system was able to find the key `e28`. But for some reason I was still not able to connect even after following the notes. 

I retraced my steps and figured out that somehow my SSH key was not successfully added to github. After fixing that, it worked fine! 

@claudiomanuelboston  You said you were able to fix the issue? Would love to hear you got yours to work!

**Comment by claudiomanuelboston** [comment]
Hello,
The issue was with commander tool, after I used git-bash I got it to work.

**Comment by susanBuck** [comment]
@gpunzalan18 Glad you were able to narrow down the source of the problem! 👍

@claudiomanuelboston Using git-bash is an acceptable workaround. I don't think you'll run into any road blocks with it as you continue.

I'm still curious/would be interested in resolving the underlying Cmder issue though.

In a post above you noted:

```
I fixed this issue : debug1: Reading configuration data
C:\\Users\\Susan/.ssh/config, It is point to the right place. I will
```

Does this mean you were able to get Cmder to read the correct config file?

**Comment by susanBuck** [comment]
Side note for anyone reading this thread or facing similar problem. I updated the ["Troubleshooting" section of the Github setup notes](https://hesweb.dev/e28/notes#/git/github?jump=troubleshooting) with some extra details and techniques that may be helpful.

**Comment by claudiomanuelboston** [comment]
Susan,
I never got Cmdr to work (printscreen attached), the same command from the
same directory.
I created a different github account, used a different computer and got the
same problem.
Thanks
Claudio

**Comment by susanBuck** [comment]
Ok, thanks for the follow-up @claudiomanuelboston. I'm going to close this thread since you found a workaround, but I'll continue to investigate and keep an eye out for other students who may run into the same problem.
